### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dcousens** [JedWatson/react-date-select#4]
Necessary functionality:
* onChange handlers
* selected
* highlighted
* [], (), [), (] range selection props

The Calendar and its associated UI component should be separate,  with the UI component being entirely stateless, and the primary Calendar component being easy to use w/ sane default functionality for every-day usage.

Examples
- [ ] Inline calendar w/ date selection
- [ ] Modal version w/ confirmation state handling around date selection
- [ ] Input field w/ modal version

All the above examples,  but with two calendars side-by-side for the range picking.

**Comment by dcousens** [comment]
@JedWatson I'm going to close unless someone else wants to pick up the https://github.com/JedWatson/react-date-select/tree/refacto branch.
